apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
data:
  AIRFLOW__CORE__DAGS_FOLDER: "/var/lib/airflow-dags/sync"
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__CORE__REMOTE_LOGGING: "False"
  AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "60"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
